apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: {{ .Values.images.adminServer.repository }}:{{ .Values.images.adminServer.tag }}
        ports:
        - name: http
          containerPort: {{ .Values.services.adminServer.port }}
          protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: admin-server-service
spec:
  type: {{ .Values.services.adminServer.type }}
  selector:
    app: admin-server
  ports:
    - port:  {{ .Values.services.adminServer.port }}
      targetPort: {{ .Values.services.adminServer.port }}
