apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: {{ .Values.images.apiGateway.repository }}:{{ .Values.images.apiGateway.tag }}
        ports:
        - name: http
          containerPort: {{ .Values.services.apiGateway.port }}
          protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    matchLabels:
      app: api-gateway
  ports:
    - port:  {{ .Values.services.apiGateway.port }}
      targetPort: {{ .Values.services.apiGateway.port }}
      type: {{ .Values.services.apiGateway.type }}
