apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: {{ .Values.images.configServer.repository }}:{{ .Values.images.configServer.tag }}
        ports:
        - name: http
          containerPort: {{ .Values.services.configServer.port }}
          protocol: TCP
        env:
          - name: EUREKA_INSTANCE_HOSTNAME
            value: config-server
--- 
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  type: {{ .Values.services.configServer.type }}
  selector:
    app: config-server
  ports:
    - port:  {{ .Values.services.configServer.port }}
      targetPort: {{ .Values.services.configServer.port }}
