apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      initContainers:
      - name: wait-for-config-server
        image: busybox
        command: ['sh', '-c', 'until wget --spider --quiet http://config-server:{{ .Values.services.configServer.port }}; do echo waiting for config-server; sleep 2; done']
      containers:
      - name: discovery-server
        image: {{ .Values.images.discoveryServer.repository }}:{{ .Values.images.discoveryServer.tag }}
        ports:
        - name: http
          containerPort: {{ .Values.services.discoveryServer.port }}
          protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  type: {{ .Values.services.discoveryServer.type }}
  selector:
    app: discovery-server
  ports:
    - port:  {{ .Values.services.discoveryServer.port }}
      targetPort: {{ .Values.services.discoveryServer.port }}
