apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: {{ .Values.images.discoveryServer.repository }}:{{ .Values.images.discoveryServer.tag }}
        ports:
        - name: http
          containerPort: {{ .Values.services.discoveryServer.port }}
          protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: discovery-server-service
spec:
  type: {{ .Values.services.discoveryServer.type }}
  selector:
    app: discovery-server
  ports:
    - port:  {{ .Values.services.discoveryServer.port }}
      targetPort: {{ .Values.services.discoveryServer.port }}
