{{- range $key, $value := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: {{ $value.type }}
  selector:
    app: {{ $value.name }}
  ports:
    - port:  {{ $value.port }}
      targetPort: {{ $value.port }}
---
{{- end }}