{{- range $key, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: {{ $service.type }}
  selector:
    app: {{ $service.name }}
  ports:
    - port:  {{ $service.port }}
      targetPort: {{ $service.port }}
{{- end }}