apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      initContainers:
      - name: wait-for-config-server
        image: busybox
        command: ['sh', '-c', 'until nslookup config-server-service; do echo waiting for config-server; sleep 2; done']
      - name: wait-for-discovery-server
        image: busybox
        command: ['sh', '-c', 'until nslookup discovery-server-service; do echo waiting for discovery-server; sleep 2; done']
      containers:
      - name: vets-service
        image: {{ .Values.images.vetsService.repository }}:{{ .Values.images.vetsService.tag }}
        ports:
        - name: http
          containerPort: {{ .Values.services.vetsService.port }}
          protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: vets-service-service
spec:
  type: {{ .Values.services.vetsService.type }}
  selector:
    app: vets-service
  ports:
    - port:  {{ .Values.services.vetsService.port }}
      targetPort: {{ .Values.services.vetsService.port }}
