apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      initContainers:
      - name: wait-for-config-server
        image: busybox
        command: ['sh', '-c', 'until wget --spider --quiet http://config-server:{{ .Values.services.configServer.port }}; do echo waiting for config-server; sleep 2; done']
      - name: wait-for-discovery-server
        image: busybox
        command: ['sh', '-c', 'until wget --spider --quiet http://discovery-server:{{ .Values.services.discoveryServer.port }}; do echo waiting for discovery-server; sleep 2; done']
      containers:
      - name: visits-service
        image: {{ .Values.images.visitsService.repository }}:{{ .Values.images.visitsService.tag }}
        ports:
        - name: http
          containerPort: {{ .Values.services.visitsService.port }}
          protocol: TCP
        env:
          - name: EUREKA_INSTANCE_HOSTNAME
            value: visits-service
--- 
apiVersion: v1
kind: Service
metadata:
  name: visits-service
spec:
  type: {{ .Values.services.visitsService.type }}
  selector:
    app: visits-service
  ports:
    - port:  {{ .Values.services.visitsService.port }}
      targetPort: {{ .Values.services.visitsService.port }}
