apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - name: visits-service
        image: {{ .Values.images.visitsService.repository }}:{{ .Values.images.visitsService.tag }}
        ports:
        - name: http
          containerPort: {{ .Values.services.visitsService.port }}
          protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: visits-service-service
spec:
  selector:
    matchLabels:
      app: visits-service
  ports:
    - port:  {{ .Values.services.visitsService.port }}
      targetPort: {{ .Values.services.visitsService.port }}
      type: {{ .Values.services.visitsService.type }}
