pipeline {
    agent any

    parameters {
        string(name: 'customers-service', defaultValue: 'main', description: '')
        string(name: 'visits-service', defaultValue: 'main', description: '')
        string(name: 'vets-service', defaultValue: 'main', description: '')
        string(name: 'genai-service', defaultValue: 'main', description: '')
    }

    stages {
        stage ('Deploy') {
            steps {
                script {
                    sh """
                        sudo su
                        kubectl get nodes -o wide
                        helm upgrade --install my-app ../my-app
                    """
                }
            }
        }

        stage ('Post Deployment') {
            steps {
                script {
                    def NODE_PORT = sh(script: 'kubectl get svc visits-service -o jsonpath="{.spec.ports[0].nodePort}"', returnStdout: true).trim()
                    def MINIKUBE_IP = sh(script: "minikube ip", returnStdout: true).trim()
                    echo "✅ App available at: http://${MINIKUBE_IP}:${NODE_PORT}"
                }
            }
        }
    }
}