pipeline {
    agent any

    environment {
        KUBECONFIG = '/home/huyen/.kube/config'
    }

    parameters {
        string(name: 'customers-service', defaultValue: 'main', description: '')
        string(name: 'visits-service', defaultValue: 'main', description: '')
        string(name: 'vets-service', defaultValue: 'main', description: '')
        string(name: 'genai-service', defaultValue: 'main', description: '')
    }

    stages {
        stage ('Deploy') {
            steps {
                script {
                    // sh """
                    //     export KUBECONFIG=/home/huyen/.kube/config
                    //     helm upgrade --install my-app ./my-app
                    // """
                    echo "kubectl get nodes"
                }
            }
        }

        stage ('Post Deployment') {
            steps {
                script {
                    def NODE_PORT = sh(script: 'kubectl get svc api-gateway -o jsonpath="{.spec.ports[0].nodePort}"', returnStdout: true).trim()
                    def MINIKUBE_IP = sh(script: "minikube ip", returnStdout: true).trim()
                    echo "✅ App available at: http://spring-petclinic:${NODE_PORT}"
                }
            }
        }
    }
}